---
apiVersion: v1
kind: Service
metadata:
  name: mongoexpress
  labels:
    name: mongoexpress-service
    app: profile-app
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30001
  selector:
    name: mongoexpress-pod
    app: profile-app