---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb-service
    app: profile-app
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30003
  selector:
    name: mongodb-pod
    app: profile-app