---
apiVersion: v1
kind: Service
metadata:
  name: simple-profile-service
  labels:
    name: simple-profile-service
    app: profile-app
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30002
  selector:
    name: simple-app-pod
    app: profile-app